--------------------------------------------------------
--  File creato - martedì-dicembre-03-2024   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Sequence HIBERNATE_SEQUENCE
--------------------------------------------------------

   CREATE SEQUENCE  "C##NERVHIBERNATE"."HIBERNATE_SEQUENCE"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
--------------------------------------------------------
--  DDL for Table USERS
--------------------------------------------------------

  CREATE TABLE "C##NERVHIBERNATE"."USERS" 
   (	"USERID" NUMBER(10,0) GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE , 
	"NAME" VARCHAR2(255 CHAR), 
	"PASSWORD" VARCHAR2(255 CHAR), 
	"SURNAME" VARCHAR2(255 CHAR), 
	"USERNAME" VARCHAR2(255 CHAR), 
	"IMAGE" BLOB
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" 
 LOB ("IMAGE") STORE AS SECUREFILE (
  TABLESPACE "USERS" ENABLE STORAGE IN ROW CHUNK 8192
  NOCACHE LOGGING  NOCOMPRESS  KEEP_DUPLICATES 
  STORAGE(INITIAL 106496 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) ;
--------------------------------------------------------
--  DDL for Table MEMBERS
--------------------------------------------------------

  CREATE TABLE "C##NERVHIBERNATE"."MEMBERS" 
   (	"MEMBERID" NUMBER(10,0) GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE , 
	"ALIAS" VARCHAR2(255 CHAR), 
	"NAME" VARCHAR2(255 CHAR), 
	"SURNAME" VARCHAR2(255 CHAR)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table MISSION
--------------------------------------------------------

  CREATE TABLE "C##NERVHIBERNATE"."MISSION" 
   (	"MISSIONID" NUMBER(10,0) GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE , 
	"EXP" NUMBER(10,0), 
	"LEVELMIN" NUMBER(10,0), 
	"SUPPORTABILITY" NUMBER(10,0), 
	"SYNCHRONIZATIONRATE" NUMBER(10,0), 
	"TACTICALABILITY" NUMBER(10,0), 
	"DURATIONTIME" NUMBER(10,0), 
	"NAME" VARCHAR2(255 CHAR), 
	"DESCRIPTION" VARCHAR2(255 CHAR), 
	"IMAGE" BLOB, 
	"PARTICIPANTSMAX" NUMBER(10,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" 
 LOB ("IMAGE") STORE AS SECUREFILE (
  TABLESPACE "USERS" ENABLE STORAGE IN ROW CHUNK 8192
  NOCACHE LOGGING  NOCOMPRESS  KEEP_DUPLICATES 
  STORAGE(INITIAL 106496 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) ;
--------------------------------------------------------
--  DDL for Table MISSION_ARCHIVE
--------------------------------------------------------

  CREATE TABLE "C##NERVHIBERNATE"."MISSION_ARCHIVE" 
   (	"MISSIONARCHIVEID" NUMBER(10,0) GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE , 
	"ENDTIME" TIMESTAMP (6), 
	"MISSIONCODE" VARCHAR2(255 CHAR), 
	"RESULT" VARCHAR2(255 CHAR), 
	"STARTTIME" TIMESTAMP (6), 
	"SUPPORTABILITY" NUMBER(10,0), 
	"SYNCHRATE" NUMBER(10,0), 
	"TACTICALABILITY" NUMBER(10,0), 
	"MEMBERID" NUMBER(10,0), 
	"MISSIONID" NUMBER(10,0), 
	"USERID" NUMBER(10,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table MISSION_PARTICIPANTS
--------------------------------------------------------

  CREATE TABLE "C##NERVHIBERNATE"."MISSION_PARTICIPANTS" 
   (	"MISSIONPARTICIPANTSID" NUMBER(10,0) GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE , 
	"MEMBERID" NUMBER(10,0), 
	"MISSIONID" NUMBER(10,0), 
	"USERID" NUMBER(10,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table SIMULATION_PARTICIPANTS
--------------------------------------------------------

  CREATE TABLE "C##NERVHIBERNATE"."SIMULATION_PARTICIPANTS" 
   (	"SIMULATIONPARTICIPANTID" NUMBER(10,0) GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE , 
	"ENDTIME" TIMESTAMP (6), 
	"STARTTIME" TIMESTAMP (6), 
	"MEMBERID" NUMBER(10,0), 
	"SIMULATIONID" NUMBER(10,0), 
	"USERID" NUMBER(10,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table SIMULATIONS
--------------------------------------------------------

  CREATE TABLE "C##NERVHIBERNATE"."SIMULATIONS" 
   (	"SIMULATIONID" NUMBER(10,0) GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE , 
	"EXP" NUMBER(10,0), 
	"LEVELMIN" NUMBER(10,0), 
	"SUPPORTABILITY" NUMBER(10,0), 
	"SYNCHRONIZATIONRATE" NUMBER(10,0), 
	"TACTICALABILITY" NUMBER(10,0), 
	"DURATIONTIME" NUMBER(10,0), 
	"NAME" VARCHAR2(255 CHAR)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table USERMEMBERS_STATS
--------------------------------------------------------

  CREATE TABLE "C##NERVHIBERNATE"."USERMEMBERS_STATS" 
   (	"IDMEMBERSTATS" NUMBER(10,0) GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE , 
	"EXP" NUMBER(10,0), 
	"LEVELPG" NUMBER(10,0), 
	"SUPPORTABILITY" NUMBER(10,0), 
	"SYNCHRONIZATIONRATE" NUMBER(10,0), 
	"TACTICALABILITY" NUMBER(10,0), 
	"STATUS" NUMBER(1,0), 
	"MEMBERID" NUMBER(10,0), 
	"USERID" NUMBER(10,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
REM INSERTING into C##NERVHIBERNATE.MEMBERS
SET DEFINE OFF;
Insert into C##NERVHIBERNATE.MEMBERS (ALIAS,NAME,SURNAME) values ('First Children','Rei','Ayanami');
Insert into C##NERVHIBERNATE.MEMBERS (ALIAS,NAME,SURNAME) values ('Second Children','Asuka','Soryu Langley');
Insert into C##NERVHIBERNATE.MEMBERS (ALIAS,NAME,SURNAME) values ('Third Children','Shinji','Ikari');
REM INSERTING into C##NERVHIBERNATE.MISSION
SET DEFINE OFF;
Insert into C##NERVHIBERNATE.MISSION (EXP,LEVELMIN,SUPPORTABILITY,SYNCHRONIZATIONRATE,TACTICALABILITY,DURATIONTIME,NAME,DESCRIPTION,PARTICIPANTSMAX) values ('100','2','25','40','35','5','Angel Attack','A giant angel, Sachiel, emerges from the sea, heading toward Neo Tokyo-3. Conventional defenses are useless. NERV deploys Evangelion, but the angel shows incredible resistance and regeneration.','1');
Insert into C##NERVHIBERNATE.MISSION (EXP,LEVELMIN,SUPPORTABILITY,SYNCHRONIZATIONRATE,TACTICALABILITY,DURATIONTIME,NAME,DESCRIPTION,PARTICIPANTSMAX) values ('200','1','35','50','30','6','A Transfer','Shamshel, an angel with energy whips, attacks the city. Its agility and lethality force Evangelion into close combat to stop it.','2');
Insert into C##NERVHIBERNATE.MISSION (EXP,LEVELMIN,SUPPORTABILITY,SYNCHRONIZATIONRATE,TACTICALABILITY,DURATIONTIME,NAME,DESCRIPTION,PARTICIPANTSMAX) values ('300','15','40','60','45','7','Showdown in Tokyo-3','Ramiel, a geometric angel, hovers over Neo Tokyo-3. Its devastating energy beam repels all attacks. Only a long-range strategy can stop it.','2');
Insert into C##NERVHIBERNATE.MISSION (EXP,LEVELMIN,SUPPORTABILITY,SYNCHRONIZATIONRATE,TACTICALABILITY,DURATIONTIME,NAME,DESCRIPTION,PARTICIPANTSMAX) values ('300','20','60','70','55','8','Asuka Strikes!','An angel attacks a military fleet from the sea. Fighting Gaghiel underwater tests Evangelion''s ability to adapt to harsh marine conditions.','2');
Insert into C##NERVHIBERNATE.MISSION (EXP,LEVELMIN,SUPPORTABILITY,SYNCHRONIZATIONRATE,TACTICALABILITY,DURATIONTIME,NAME,DESCRIPTION,PARTICIPANTSMAX) values ('350','25','65','75','65','9','Both of You, Dance Like You Want to Win!','Israfel splits into two synchronized entities. The mission requires perfect cooperation to strike both targets at the same time.','2');
Insert into C##NERVHIBERNATE.MISSION (EXP,LEVELMIN,SUPPORTABILITY,SYNCHRONIZATIONRATE,TACTICALABILITY,DURATIONTIME,NAME,DESCRIPTION,PARTICIPANTSMAX) values ('350','30','55','60','70','10','Magma Diver','A dormant angel awakens inside a volcano. The mission to capture Sandalphon turns into a desperate fight in a volatile environment.','1');
Insert into C##NERVHIBERNATE.MISSION (EXP,LEVELMIN,SUPPORTABILITY,SYNCHRONIZATIONRATE,TACTICALABILITY,DURATIONTIME,NAME,DESCRIPTION,PARTICIPANTSMAX) values ('400','35','45','50','60','10','The Day Tokyo-3 Stood Still','During a blackout, Matarael attacks Neo Tokyo-3 with acid. With no technology available, improvised solutions are the only hope.','2');
Insert into C##NERVHIBERNATE.MISSION (EXP,LEVELMIN,SUPPORTABILITY,SYNCHRONIZATIONRATE,TACTICALABILITY,DURATIONTIME,NAME,DESCRIPTION,PARTICIPANTSMAX) values ('900','40','75','65','80','11','She Said, Don''t Make Others Suffer','Sahaquiel, a giant angel, tries to crash into Neo Tokyo-3. Interception is critical, but its size and ranged attacks make it a challenge.','2');
Insert into C##NERVHIBERNATE.MISSION (EXP,LEVELMIN,SUPPORTABILITY,SYNCHRONIZATIONRATE,TACTICALABILITY,DURATIONTIME,NAME,DESCRIPTION,PARTICIPANTSMAX) values ('950','50','80','55','60','12','Lilliputian Hitcher','A microscopic angel invades NERV, infecting its systems. The mission demands intelligence to outsmart the rapidly evolving enemy.','1');
Insert into C##NERVHIBERNATE.MISSION (EXP,LEVELMIN,SUPPORTABILITY,SYNCHRONIZATIONRATE,TACTICALABILITY,DURATIONTIME,NAME,DESCRIPTION,PARTICIPANTSMAX) values ('500','60','60','70','50','13','Oral Stage','A parasitic angel infects an Evangelion, using it to attack. The mission is to stop Bardiel without destroying the infected unit.','3');
Insert into C##NERVHIBERNATE.MISSION (EXP,LEVELMIN,SUPPORTABILITY,SYNCHRONIZATIONRATE,TACTICALABILITY,DURATIONTIME,NAME,DESCRIPTION,PARTICIPANTSMAX) values ('450','65','65','80','70','14','Splitting of the Breast','Leliel appears as a giant black sphere. Its two-dimensional shadow warps reality, making entry into its dimension the only option.','2');
Insert into C##NERVHIBERNATE.MISSION (EXP,LEVELMIN,SUPPORTABILITY,SYNCHRONIZATIONRATE,TACTICALABILITY,DURATIONTIME,NAME,DESCRIPTION,PARTICIPANTSMAX) values ('950','70','85','85','90','15','Ambivalence','Zeruel, an angel of massive power, attacks NERV, breaking defenses with energy blasts and blades. Only a direct confrontation can stop it.','3');
Insert into C##NERVHIBERNATE.MISSION (EXP,LEVELMIN,SUPPORTABILITY,SYNCHRONIZATIONRATE,TACTICALABILITY,DURATIONTIME,NAME,DESCRIPTION,PARTICIPANTSMAX) values ('1000','80','90','90','80','16','Introjection','Zeruel''s attack on NERV intensifies. The pilots must risk everything in a desperate battle to stop its devastating advance.','3');
Insert into C##NERVHIBERNATE.MISSION (EXP,LEVELMIN,SUPPORTABILITY,SYNCHRONIZATIONRATE,TACTICALABILITY,DURATIONTIME,NAME,DESCRIPTION,PARTICIPANTSMAX) values ('1500','85','70','65','55','17','He Was Aware That He Was Still a Child','Arael attacks with a psychic assault from orbit. The mission challenges both the pilots'' physical and emotional resilience.','2');
Insert into C##NERVHIBERNATE.MISSION (EXP,LEVELMIN,SUPPORTABILITY,SYNCHRONIZATIONRATE,TACTICALABILITY,DURATIONTIME,NAME,DESCRIPTION,PARTICIPANTSMAX) values ('2000','90','80','90','75','18','Don''t Be','Armisael, a fluid angel, threatens to merge with the Evangelion units. The mission is to stop it before its dangerous connection is complete.','2');
Insert into C##NERVHIBERNATE.MISSION (EXP,LEVELMIN,SUPPORTABILITY,SYNCHRONIZATIONRATE,TACTICALABILITY,DURATIONTIME,NAME,DESCRIPTION,PARTICIPANTSMAX) values ('3000','100','85','100','90','20','Kaworu Nagisa','Tabris infiltrates NERV, blurring the line between ally and enemy. The mission is to prevent him from reaching Terminal Dogma.','3');
Insert into C##NERVHIBERNATE.MISSION (EXP,LEVELMIN,SUPPORTABILITY,SYNCHRONIZATIONRATE,TACTICALABILITY,DURATIONTIME,NAME,DESCRIPTION,PARTICIPANTSMAX) values ('5000','100','100','100','100','25','Take Care of Yourself','The final mission is a personal battle against inner demons. The pilots must confront their fears in a race against time.','3');
REM INSERTING into C##NERVHIBERNATE.MISSION_ARCHIVE
SET DEFINE OFF;
REM INSERTING into C##NERVHIBERNATE.MISSION_PARTICIPANTS
SET DEFINE OFF;
REM INSERTING into C##NERVHIBERNATE.SIMULATION_PARTICIPANTS
SET DEFINE OFF;
REM INSERTING into C##NERVHIBERNATE.SIMULATIONS
SET DEFINE OFF;
Insert into C##NERVHIBERNATE.SIMULATIONS (EXP,LEVELMIN,SUPPORTABILITY,SYNCHRONIZATIONRATE,TACTICALABILITY,DURATIONTIME,NAME) values ('100','0','10','10','-20','1','RESCUE MISSION');
Insert into C##NERVHIBERNATE.SIMULATIONS (EXP,LEVELMIN,SUPPORTABILITY,SYNCHRONIZATIONRATE,TACTICALABILITY,DURATIONTIME,NAME) values ('100','0','10','-20','10','1','INFILTRATION MISSION');
Insert into C##NERVHIBERNATE.SIMULATIONS (EXP,LEVELMIN,SUPPORTABILITY,SYNCHRONIZATIONRATE,TACTICALABILITY,DURATIONTIME,NAME) values ('100','0','-20','10','10','1','ANGEL FIGHT');
--------------------------------------------------------
--  DDL for Index UK_DC4EQ7PLR20FDHQ528TWSAK1B
--------------------------------------------------------

  CREATE UNIQUE INDEX "C##NERVHIBERNATE"."UK_DC4EQ7PLR20FDHQ528TWSAK1B" ON "C##NERVHIBERNATE"."USERS" ("USERNAME") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C009693
--------------------------------------------------------

  CREATE UNIQUE INDEX "C##NERVHIBERNATE"."SYS_C009693" ON "C##NERVHIBERNATE"."USERS" ("USERID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C009678
--------------------------------------------------------

  CREATE UNIQUE INDEX "C##NERVHIBERNATE"."SYS_C009678" ON "C##NERVHIBERNATE"."MEMBERS" ("MEMBERID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C009680
--------------------------------------------------------

  CREATE UNIQUE INDEX "C##NERVHIBERNATE"."SYS_C009680" ON "C##NERVHIBERNATE"."MISSION" ("MISSIONID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C009682
--------------------------------------------------------

  CREATE UNIQUE INDEX "C##NERVHIBERNATE"."SYS_C009682" ON "C##NERVHIBERNATE"."MISSION_ARCHIVE" ("MISSIONARCHIVEID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C009684
--------------------------------------------------------

  CREATE UNIQUE INDEX "C##NERVHIBERNATE"."SYS_C009684" ON "C##NERVHIBERNATE"."MISSION_PARTICIPANTS" ("MISSIONPARTICIPANTSID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C009686
--------------------------------------------------------

  CREATE UNIQUE INDEX "C##NERVHIBERNATE"."SYS_C009686" ON "C##NERVHIBERNATE"."SIMULATION_PARTICIPANTS" ("SIMULATIONPARTICIPANTID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C009688
--------------------------------------------------------

  CREATE UNIQUE INDEX "C##NERVHIBERNATE"."SYS_C009688" ON "C##NERVHIBERNATE"."SIMULATIONS" ("SIMULATIONID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C009690
--------------------------------------------------------

  CREATE UNIQUE INDEX "C##NERVHIBERNATE"."SYS_C009690" ON "C##NERVHIBERNATE"."USERMEMBERS_STATS" ("IDMEMBERSTATS") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Constraints for Table USERS
--------------------------------------------------------

  ALTER TABLE "C##NERVHIBERNATE"."USERS" MODIFY ("USERID" NOT NULL ENABLE);
  ALTER TABLE "C##NERVHIBERNATE"."USERS" MODIFY ("USERNAME" NOT NULL ENABLE);
  ALTER TABLE "C##NERVHIBERNATE"."USERS" ADD PRIMARY KEY ("USERID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "C##NERVHIBERNATE"."USERS" ADD CONSTRAINT "UK_DC4EQ7PLR20FDHQ528TWSAK1B" UNIQUE ("USERNAME")
  USING INDEX "C##NERVHIBERNATE"."UK_DC4EQ7PLR20FDHQ528TWSAK1B"  ENABLE;
--------------------------------------------------------
--  Constraints for Table MEMBERS
--------------------------------------------------------

  ALTER TABLE "C##NERVHIBERNATE"."MEMBERS" MODIFY ("MEMBERID" NOT NULL ENABLE);
  ALTER TABLE "C##NERVHIBERNATE"."MEMBERS" ADD PRIMARY KEY ("MEMBERID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table MISSION
--------------------------------------------------------

  ALTER TABLE "C##NERVHIBERNATE"."MISSION" MODIFY ("MISSIONID" NOT NULL ENABLE);
  ALTER TABLE "C##NERVHIBERNATE"."MISSION" ADD PRIMARY KEY ("MISSIONID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table MISSION_ARCHIVE
--------------------------------------------------------

  ALTER TABLE "C##NERVHIBERNATE"."MISSION_ARCHIVE" MODIFY ("MISSIONARCHIVEID" NOT NULL ENABLE);
  ALTER TABLE "C##NERVHIBERNATE"."MISSION_ARCHIVE" ADD PRIMARY KEY ("MISSIONARCHIVEID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table MISSION_PARTICIPANTS
--------------------------------------------------------

  ALTER TABLE "C##NERVHIBERNATE"."MISSION_PARTICIPANTS" MODIFY ("MISSIONPARTICIPANTSID" NOT NULL ENABLE);
  ALTER TABLE "C##NERVHIBERNATE"."MISSION_PARTICIPANTS" ADD PRIMARY KEY ("MISSIONPARTICIPANTSID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table SIMULATION_PARTICIPANTS
--------------------------------------------------------

  ALTER TABLE "C##NERVHIBERNATE"."SIMULATION_PARTICIPANTS" MODIFY ("SIMULATIONPARTICIPANTID" NOT NULL ENABLE);
  ALTER TABLE "C##NERVHIBERNATE"."SIMULATION_PARTICIPANTS" ADD PRIMARY KEY ("SIMULATIONPARTICIPANTID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table SIMULATIONS
--------------------------------------------------------

  ALTER TABLE "C##NERVHIBERNATE"."SIMULATIONS" MODIFY ("SIMULATIONID" NOT NULL ENABLE);
  ALTER TABLE "C##NERVHIBERNATE"."SIMULATIONS" ADD PRIMARY KEY ("SIMULATIONID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table USERMEMBERS_STATS
--------------------------------------------------------

  ALTER TABLE "C##NERVHIBERNATE"."USERMEMBERS_STATS" MODIFY ("IDMEMBERSTATS" NOT NULL ENABLE);
  ALTER TABLE "C##NERVHIBERNATE"."USERMEMBERS_STATS" ADD PRIMARY KEY ("IDMEMBERSTATS")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table MISSION_ARCHIVE
--------------------------------------------------------

  ALTER TABLE "C##NERVHIBERNATE"."MISSION_ARCHIVE" ADD CONSTRAINT "FKP49EJK645VX5J6MIU0S42BMGA" FOREIGN KEY ("MEMBERID")
	  REFERENCES "C##NERVHIBERNATE"."MEMBERS" ("MEMBERID") ENABLE;
  ALTER TABLE "C##NERVHIBERNATE"."MISSION_ARCHIVE" ADD CONSTRAINT "FKIDWOCO4PFBPLNHNKK0LIELSNU" FOREIGN KEY ("MISSIONID")
	  REFERENCES "C##NERVHIBERNATE"."MISSION" ("MISSIONID") ENABLE;
  ALTER TABLE "C##NERVHIBERNATE"."MISSION_ARCHIVE" ADD CONSTRAINT "FK60F30SM29C2V3TBCBFK1A526B" FOREIGN KEY ("USERID")
	  REFERENCES "C##NERVHIBERNATE"."USERS" ("USERID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table MISSION_PARTICIPANTS
--------------------------------------------------------

  ALTER TABLE "C##NERVHIBERNATE"."MISSION_PARTICIPANTS" ADD CONSTRAINT "FKSUXD7XLHQ3B7GDTEX189M29OE" FOREIGN KEY ("MEMBERID")
	  REFERENCES "C##NERVHIBERNATE"."MEMBERS" ("MEMBERID") ENABLE;
  ALTER TABLE "C##NERVHIBERNATE"."MISSION_PARTICIPANTS" ADD CONSTRAINT "FKD7W31KFBB4P8YQXV6GHAIYAVK" FOREIGN KEY ("MISSIONID")
	  REFERENCES "C##NERVHIBERNATE"."MISSION" ("MISSIONID") ENABLE;
  ALTER TABLE "C##NERVHIBERNATE"."MISSION_PARTICIPANTS" ADD CONSTRAINT "FK16BIPHO844NE3HVF69WWXVUYJ" FOREIGN KEY ("USERID")
	  REFERENCES "C##NERVHIBERNATE"."USERS" ("USERID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table SIMULATION_PARTICIPANTS
--------------------------------------------------------

  ALTER TABLE "C##NERVHIBERNATE"."SIMULATION_PARTICIPANTS" ADD CONSTRAINT "FKE3YGWK0O89JLCOC0R088WHOLE" FOREIGN KEY ("MEMBERID")
	  REFERENCES "C##NERVHIBERNATE"."MEMBERS" ("MEMBERID") ENABLE;
  ALTER TABLE "C##NERVHIBERNATE"."SIMULATION_PARTICIPANTS" ADD CONSTRAINT "FKOYHWASJ9J7MF7S9RFG51JYMA5" FOREIGN KEY ("SIMULATIONID")
	  REFERENCES "C##NERVHIBERNATE"."SIMULATIONS" ("SIMULATIONID") ENABLE;
  ALTER TABLE "C##NERVHIBERNATE"."SIMULATION_PARTICIPANTS" ADD CONSTRAINT "FKLN6RK7BAI54TEY9904OBXM23E" FOREIGN KEY ("USERID")
	  REFERENCES "C##NERVHIBERNATE"."USERS" ("USERID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table USERMEMBERS_STATS
--------------------------------------------------------

  ALTER TABLE "C##NERVHIBERNATE"."USERMEMBERS_STATS" ADD CONSTRAINT "FKALKNQXI3KR8F2VW9QEQJTCF19" FOREIGN KEY ("MEMBERID")
	  REFERENCES "C##NERVHIBERNATE"."MEMBERS" ("MEMBERID") ENABLE;
  ALTER TABLE "C##NERVHIBERNATE"."USERMEMBERS_STATS" ADD CONSTRAINT "FKOEGOT7Q2T64YL6TSBRKWUF8JC" FOREIGN KEY ("USERID")
	  REFERENCES "C##NERVHIBERNATE"."USERS" ("USERID") ENABLE;
